services:
  linda-frontend:
    build: ./
    ports:
      - "8001:8001"
    networks:
      - custom_network
    container_name: linda_frontend
    env_file: ".env"
    command: /bin/bash ./entrypoint.sh
    volumes:
      - website_volume:/website
    working_dir: /website
    stdin_open: true
    tty: true

volumes:
  website_volume:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}
      o: bind

networks:
  custom_network:
    external: true
